// Generated by IcedCoffeeScript 108.0.11
(function() {
  angular.module('app.controllers').controller('PublicatorController', function($scope, record) {
    var blankModel;
    blankModel = function() {
      return {
        r: record
      };
    };
    $scope.x = record;
    console.log('hi');
    console.log(record);
    return $scope.publishAsOpenData = function() {
      if (!$scope.form.publication) {
        $scope.form.publication = {};
      }
      if (!$scope.form.publication.openData) {
        return $scope.form.publication.openData = {
          lastAttempt: {},
          lastSuccess: {}
        };
      }
    };
  });

}).call(this);

//# sourceMappingURL=PublicatorController.js.map
