// Generated by IcedCoffeeScript 108.0.9
(function() {
  angular.module('app.controllers').controller('PublicatorController', function($scope) {
    var blankModel;
    blankModel = function() {
      return {
        q: '',
        r: []
      };
    };
    return $scope.publishAsOpenData = function() {
      if (!$scope.form.publication) {
        $scope.form.publication = {};
      }
      if (!$scope.form.publication.openData) {
        return $scope.form.publication.openData = {
          lastAttempt: {},
          lastSuccess: {}
        };
      }
    };
  });

}).call(this);

//# sourceMappingURL=PublicatorController.js.map
